### ISSUE TITLE
February Product Update 2024

### ISSUE THREAD

**Issue by aroojarshad12** [n3oltd/support#174]
```[tasklist]
### Tasks
- [ ] Card Terminal Payment Method: https://github.com/n3oltd/K2.React/issues/440
```

**Comment by nadrummond** [comment]
@aroojarshad12 @RehanSalim-N3O Auto pause/cancel regular giving when pledge complete or cancelled, auto-adjust final payment for regular giving linked to pledges, auto-update donations when pledge edited, textmarketer / helpwise integrations added, UI for managing stored credentials (DDs / cards), ability to store electronic mandate copies alongside credentials, Netcash added, Square payments added,
