### ISSUE TITLE
Product Update: April 2024

### ISSUE THREAD

**Issue by aroojarshad12** [n3oltd/support#207]
**Tasks List**
- [x] What's New 
- [x] Fixed Bugs 
- [x] Coming Up

**Comment by waheed-n3o** [comment]
https://github.com/n3oltd/K2.React/pull/541

https://github.com/n3oltd/K2.React/pull/537

https://github.com/n3oltd/K2.React/pull/536

https://github.com/n3oltd/K2.React/pull/531

https://github.com/n3oltd/K2.React/pull/530
