### ISSUE TITLE
Product Update: May 2024

### ISSUE THREAD

**Issue by aroojarshad12** [n3oltd/support#219]
**Tasks List**
- [x] What's New 
- [x] Fixed Bugs 
- [x] Coming Up

**Comment by waheed-n3o** [comment]
1. https://github.com/n3oltd/K2.React/issues/578
2. https://github.com/n3oltd/K2.React/issues/575
3. https://github.com/n3oltd/K2.React/issues/567
4. https://github.com/n3oltd/K2.React/issues/566
5. https://github.com/n3oltd/K2.React/issues/565
6. https://github.com/n3oltd/K2.React/issues/564
7. https://github.com/n3oltd/K2.React/issues/563
8. https://github.com/n3oltd/K2.React/issues/562

**Comment by zeeshanshaheenn3o** [comment]
https://github.com/n3oltd/K2.React/issues/555 (we have introduced folder concept in list).

so one can create folders and share them with anyone.
A list can now be created inside of folder only.
we have changed the List Export View.
