### ISSUE TITLE
Adding content to GER Singapore and Malaysia Websites

### ISSUE THREAD

**Issue by aroojarshad12** [n3oltd/support#272]
https://globalehsanrelief-sg-staging.n3o.site/umbraco#/content  (Singapore)

https://globalehsanrelief-my-staging.n3o.site/umbraco  (Malaysia)

**Comment by nadrummond** [comment]
@aroojarshad12 Please don't post these tasks / issues on this repo. This repo is fully public and can be seen by anyone in the world.

**Comment by aroojarshad12** [comment]
@nadrummond for now, I am transfering this issue to the private teams repository.
