### ISSUE TITLE
Product Update: August 2024

### ISSUE THREAD

**Issue by aroojarshad12** [n3oltd/support#291]
**Tasks List**
- [x] What's New 
- [x] Fixed Bugs 
- [x] Coming Up

**Comment by sirajurrahmann** [comment]
- Analysis Report: Pivot Tables for different dimension analysis—e.g., Income By Country, Income By Date, Income By Fundraiser, etc.

**Comment by zeeshanshaheenn3o** [comment]
- Manage Reporting Period Added in Analytics
