### ISSUE TITLE
Product Update: October 2024

### ISSUE THREAD

**Issue by aroojarshad12** [n3oltd/support#322]
- [x] What's New
- [x] Bugs Fixed
- [x] Coming Up

**Comment by waheed-n3o** [comment]
Attribution: specify option removed
https://github.com/n3oltd/K2.React/pull/766

**Comment by ShaguftaN3O** [comment]
DataImport: added an option on feed level to 'Disable the pricing rules' on feedbacks, donation Item or sponsorhsips.

On feeds added an option on each entity to disable the pricing validation (let for historical data import)

**Comment by zeeshanshaheenn3o** [comment]
https://github.com/n3oltd/K2.React/pull/745

**Comment by zeeshanshaheenn3o** [comment]
https://github.com/n3oltd/client-issues/issues/990
